"""Module extension for rules_podman.

Hermetically fetches Podman for the host platform, pinned by sha256
(see `private/known_versions.bzl`), and exposes it as `@podman//:podman`
plus a ready-to-register toolchain (`@podman//:podman_toolchain_def`).

On Linux it fetches the fully-static `mgoltzsche/podman-static` bundle
and generates a launcher that wires podman to its **bundled** OCI
runtime (crun), conmon, netavark, and configs — a real **daemonless,
rootless** engine, no service to start. On macOS/Windows it fetches the
official client binary (which talks to a `podman machine`).

Default usage:

    podman = use_extension("@rules_podman//podman:extensions.bzl", "podman")
    use_repo(podman, "podman")
    register_toolchains("@podman//:podman_toolchain_def")

Pin a specific Podman version:

    podman = use_extension("@rules_podman//podman:extensions.bzl", "podman")
    podman.toolchain(version = "5.8.2")
    use_repo(podman, "podman")
"""

load(
    "//podman/private:known_versions.bzl",
    "DEFAULT_VERSION",
    "GITHUB_DOWNLOAD",
    "KNOWN_VERSIONS",
    "PLATFORMS",
)

def _resolve_platform(rctx):
    os = rctx.os.name.lower()
    arch = rctx.os.arch.lower()
    if "linux" in os and arch in ("x86_64", "amd64"):
        return "linux_amd64"
    if "linux" in os and arch in ("aarch64", "arm64"):
        return "linux_arm64"
    if ("mac" in os or "darwin" in os) and arch in ("aarch64", "arm64"):
        return "darwin_arm64"
    if ("mac" in os or "darwin" in os) and arch in ("x86_64", "amd64"):
        return "darwin_amd64"
    if "windows" in os and arch in ("x86_64", "amd64"):
        return "windows_amd64"
    if "windows" in os and arch in ("aarch64", "arm64"):
        return "windows_arm64"
    fail("rules_podman: unsupported platform os=%s arch=%s" % (os, arch))

# Launcher for the daemonless Linux engine. Resolves its own real path
# (walking symlinks) to find the extracted bundle sitting beside it, then
# points podman at the bundled runtimes/helpers/configs before exec. All
# wiring is overridable from the environment so callers can still supply
# their own containers.conf etc. `{top}` is the bundle's top-level dir.
_LINUX_LAUNCHER = """\
#!/usr/bin/env bash
# Generated by rules_podman — daemonless rootless Podman launcher.
set -euo pipefail

src="${{BASH_SOURCE[0]}}"
while [ -L "$src" ]; do
  d="$(cd -P "$(dirname "$src")" >/dev/null 2>&1 && pwd)"
  src="$(readlink "$src")"
  [[ "$src" != /* ]] && src="$d/$src"
done
HERE="$(cd -P "$(dirname "$src")" >/dev/null 2>&1 && pwd)"
ROOT="$HERE/{top}"

# Bundled crun/runc/pasta/fuse-overlayfs come first on PATH; conmon,
# netavark, aardvark-dns, rootlessport, catatonit live in the helper dir.
export PATH="$ROOT/usr/local/bin:${{PATH:-}}"
export CONTAINERS_HELPER_BINARY_DIR="${{CONTAINERS_HELPER_BINARY_DIR:-$ROOT/usr/local/lib/podman}}"
export CONTAINERS_CONF="${{CONTAINERS_CONF:-$ROOT/etc/containers/containers.conf}}"
export CONTAINERS_REGISTRIES_CONF="${{CONTAINERS_REGISTRIES_CONF:-$ROOT/etc/containers/registries.conf}}"

exec "$ROOT/usr/local/bin/podman" "$@"
"""

def _engine_build(top, version):
    """Generated BUILD for a daemonless Linux engine bundle."""
    return """\
load("@bazel_skylib//rules:native_binary.bzl", "native_binary")
load("@rules_podman//podman:toolchains.bzl", "podman_toolchain")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "all_files",
    srcs = glob(["{top}/**"], allow_empty = False),
)

# The launcher is the executable; the whole bundle rides along as
# runfiles so the launcher can locate the runtimes/helpers/configs.
native_binary(
    name = "podman",
    src = "launcher.sh",
    out = "podman",
    data = [":all_files"],
)

podman_toolchain(
    name = "podman_toolchain",
    podman = ":podman",
    version = "{version}",
    engine = True,
)

toolchain(
    name = "podman_toolchain_def",
    toolchain = ":podman_toolchain",
    toolchain_type = "@rules_podman//podman:toolchain_type",
)
""".format(top = top, version = version)

def _client_build(binary_rel, exe_suffix, version):
    """Generated BUILD for a single client binary (macOS/Windows)."""
    return """\
load("@bazel_skylib//rules:native_binary.bzl", "native_binary")
load("@rules_podman//podman:toolchains.bzl", "podman_toolchain")

package(default_visibility = ["//visibility:public"])

native_binary(
    name = "podman",
    src = "{binary_rel}",
    out = "podman{exe_suffix}",
)

podman_toolchain(
    name = "podman_toolchain",
    podman = ":podman",
    version = "{version}",
    engine = False,
)

toolchain(
    name = "podman_toolchain_def",
    toolchain = ":podman_toolchain",
    toolchain_type = "@rules_podman//podman:toolchain_type",
)
""".format(
        binary_rel = binary_rel,
        exe_suffix = exe_suffix,
        version = version,
    )

def _podman_repository_impl(rctx):
    platform = _resolve_platform(rctx)
    version = rctx.attr.version
    layout = PLATFORMS[platform]
    asset = layout["asset"].format(version = version)
    url = GITHUB_DOWNLOAD.format(repo = layout["repo"], version = version, asset = asset)

    sha256 = KNOWN_VERSIONS.get(version, {}).get(platform, "")
    if not sha256:
        # buildifier: disable=print
        print(("rules_podman: WARNING — no pinned sha256 for podman@{v} on {p}; " +
               "downloading unverified. Run `tools/refresh_versions.py " +
               "--version {v}` to lock it.").format(v = version, p = platform))

    # Keep the upstream layout intact (no stripPrefix); the launcher /
    # native_binary reference files by their full in-archive path.
    rctx.download_and_extract(url = url, sha256 = sha256 or "")

    if layout["engine"]:
        top = layout["bundle_top"]
        rctx.file("launcher.sh", _LINUX_LAUNCHER.format(top = top))
        rctx.file("BUILD.bazel", _engine_build(top, version))
    else:
        binary_rel = layout["binary"].format(version = version)
        exe_suffix = ".exe" if platform.startswith("windows") else ""
        rctx.file("BUILD.bazel", _client_build(binary_rel, exe_suffix, version))

_podman_repository = repository_rule(
    implementation = _podman_repository_impl,
    attrs = {
        "version": attr.string(
            mandatory = True,
            doc = "Podman release version to fetch (e.g. \"5.8.2\").",
        ),
    },
    doc = "Fetch the prebuilt Podman engine (Linux) or client (macOS/Windows) for the host.",
)

def _podman_extension_impl(mctx):
    # Reduce all toolchain tags across the dep graph to one version.
    # Root module wins; otherwise the last tag seen.
    version = DEFAULT_VERSION
    for mod in mctx.modules:
        for tag in mod.tags.toolchain:
            if tag.version:
                version = tag.version

    _podman_repository(name = "podman", version = version)

_toolchain_tag = tag_class(attrs = {
    "version": attr.string(
        default = "",
        doc = "Override the Podman version. Defaults to the value in known_versions.bzl.",
    ),
})

podman = module_extension(
    implementation = _podman_extension_impl,
    tag_classes = {"toolchain": _toolchain_tag},
    doc = "Sets up @podman: a daemonless static engine on Linux, the official client on macOS/Windows.",
)
